import React, { useEffect, useState } from "react";
import api from "../api";

const GenReport = ({ onClose }) => {
  const currentDate = new Date().toLocaleDateString();
  const currentTime = new Date().toLocaleTimeString();
  const [counts, setCounts] = useState({
    users: 0,
    disabledUsers: 0,
    totalUsers: 0,
    books: 0,
    activeLoans: 0,
    visitsToday: 0
  });

  useEffect(() => {
    api.get('/dashboard').then(r => setCounts((prev) => ({ ...prev, ...r.data.counts }))).catch(()=>{});
  }, []);

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4">
      <div className="relative w-full max-w-lg rounded-xl theme-panel ring-1 ring-slate-200 [[data-theme=dark]_&]:ring-stone-700 p-6">
        <button className="absolute right-3 top-3 text-slate-500 hover:text-slate-700 [[data-theme=dark]_&]:text-stone-400 [[data-theme=dark]_&]:hover:text-slate-200" onClick={onClose}>&times;</button>

        <h2 className="text-xl font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">Quick Report</h2>
        <p className="text-sm text-slate-500 [[data-theme=dark]_&]:text-stone-300 mt-1">Date: {currentDate} | Time: {currentTime}</p>

        <div className="mt-4 rounded-lg theme-panel ring-1 ring-slate-200 [[data-theme=dark]_&]:ring-stone-700 p-4">
          <h3 className="text-sm font-medium text-slate-700 [[data-theme=dark]_&]:text-stone-200">Summary</h3>
          <div className="mt-2 grid grid-cols-2 sm:grid-cols-3 gap-3 text-sm">
            <div className="flex items-center justify-between"><span className="text-slate-500">Active Users</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.users}</span></div>
            <div className="flex items-center justify-between"><span className="text-slate-500">Disabled Users</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.disabledUsers}</span></div>
            <div className="flex items-center justify-between"><span className="text-slate-500">Total Users</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.totalUsers || counts.users + counts.disabledUsers}</span></div>
            <div className="flex items-center justify-between"><span className="text-slate-500">Books Borrowed</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.activeLoans}</span></div>
            <div className="flex items-center justify-between"><span className="text-slate-500">Total Books</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.books}</span></div>
            <div className="flex items-center justify-between"><span className="text-slate-500">Visits Today</span><span className="font-semibold text-slate-900 [[data-theme=dark]_&]:text-stone-100">{counts.visitsToday}</span></div>
          </div>
        </div>

        <div className="mt-6 text-xs text-slate-500 [[data-theme=dark]_&]:text-stone-400">
          <p>Prepared by: <strong className="text-slate-700 [[data-theme=dark]_&]:text-stone-200">ADMIN</strong></p>
          <p>Generated by: LibReport System</p>
        </div>
      </div>
    </div>
  );
};

export default GenReport;
